</div>  
</div>
<footer class="footer container-fluid text-center">
<ul class="footer-nav">
<li><a href="#">About</a></li> | <li><a href="#">Help</a></li>| <li><a href="#">Contact</a></li>
</ul>
</footer>
  <!--<script src="http://www.censusscope.org/new/sites/all/themes/bootstrap/js/bootstrap.js?p2cvwb"></script>-->
<script type="text/javascript" src="../slick/slick.min.js"></script>
</body>
</html>